import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

import org.eclipse.jface.dialogs.InputDialog;
import org.eclipse.jface.window.ApplicationWindow;
import org.eclipse.swt.SWT;
import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.graphics.GC;
import org.eclipse.swt.graphics.Image;
import org.eclipse.swt.graphics.LineAttributes;
import org.eclipse.swt.graphics.Point;
import org.eclipse.swt.graphics.Rectangle;
import org.eclipse.swt.widgets.ColorDialog;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Event;
import org.eclipse.swt.widgets.FileDialog;
import org.eclipse.swt.widgets.Menu;
import org.eclipse.swt.widgets.MenuItem;
import org.eclipse.swt.widgets.MessageBox;
import org.eclipse.swt.widgets.Shell;
import org.eclipse.swt.widgets.TabFolder;
import org.eclipse.swt.widgets.TabItem;
import org.eclipse.wb.swt.SWTResourceManager;
import org.eclipse.swt.events.DragDetectEvent;
import org.eclipse.swt.events.DragDetectListener;
import org.eclipse.swt.events.KeyAdapter;
import org.eclipse.swt.events.KeyEvent;
import org.eclipse.swt.events.MouseAdapter;
import org.eclipse.swt.events.MouseEvent;
import org.eclipse.swt.events.MouseMoveListener;
import org.eclipse.swt.events.PaintEvent;
import org.eclipse.swt.events.PaintListener;
import org.eclipse.swt.events.SelectionAdapter;
import org.eclipse.swt.events.SelectionEvent;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Text;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.layout.GridData;
import org.eclipse.ui.forms.widgets.FormToolkit;
import org.eclipse.swt.browser.Browser;
import org.eclipse.swt.widgets.List;
import org.eclipse.swt.layout.FillLayout;

public class MainWindow extends ApplicationWindow
{
	private final FormToolkit formToolkit = new FormToolkit(
			Display.getDefault()); // I have no idea what this does. It was autogenerated. Don't delete it.
	
	private Text codeBox; // The textbox containing the code
	private Text txtOutput; // The textbox outputting commands and info from the project
	private Text commandLine; // The textbox for entering commands
	Composite display;// The playing field for llamas
	
	private boolean runnable; // Can we run the current project? (Is the Execution Tab open?)
	int objectBeingDragged; // The object we are moving around the display
	ArrayList<Llama> programObjects; // The objects in the program
	boolean[] selectedObject; // The objects currently selected
	Llama[] objectLabels; // The objects in the llamaBank
	List listObjects; // The list of objects in play on the field
	Browser browser; // The help browser
	String homeURL = this.getClass().getResource("/helpHome.htm").toString(); // The url for the home file
	Image defaultLlama = SWTResourceManager.getImage(MainWindow.class, "/pictures/Llama.gif"); // The default llama image
	ArrayList<Line> lines = new ArrayList<Line>(); // The lines drawn on the field by llamas
	ArrayList<Llama> frozenLlamas = new ArrayList<Llama>(); // The llamas on the field that are frozen
	ArrayList<Line> frozenLines = new ArrayList<Line>(); // The lines on the field that are frozen
	boolean frozen = false; // Whether or not there is a frozen background
	
	/**
	 * Create the application window.
	 */
	public MainWindow()
	{
		super(null);
		runnable = false;// We start in the Code tab, so we can't run anything
		objectBeingDragged = -1;// No objects are selected from the Llamabank
		programObjects = new ArrayList<Llama>(0);// Initialize the list of objects currently in play
	}
	
	/**
	 * Create contents of the application window.
	 * 
	 * @param parent
	 */
	@Override
	protected Control createContents(Composite parent)
	{
		// Begin auto-generated code from Design tab
		setStatus("");
		Composite container = new Composite(parent, SWT.NONE);
		container.setLayout(new GridLayout(1, false));
		
		Composite toolbar = new Composite(container, SWT.NONE);
		toolbar.setLayout(new FillLayout(SWT.HORIZONTAL));
		GridData gd_toolbar = new GridData(SWT.LEFT, SWT.CENTER, true, false,
				1, 1);
		gd_toolbar.widthHint = 3000;
		toolbar.setLayoutData(gd_toolbar);
		
		Button newBtn = new Button(toolbar, SWT.NONE);
		newBtn.addSelectionListener(new SelectionAdapter()
		{
			@Override
			public void widgetSelected(SelectionEvent e)
			{
				newProject();// Open a new project (see lines at bottom of class)
			}
		});
		newBtn.setText("New");
		newBtn.setToolTipText("New");
		newBtn.setImage(SWTResourceManager.getImage(MainWindow.class, "/pictures/New.gif"));
		
		Button saveBtn = new Button(toolbar, SWT.NONE);
		saveBtn.setText("Save");
		saveBtn.addSelectionListener(new SelectionAdapter()
		{
			@Override
			public void widgetSelected(SelectionEvent e)
			{
				saveProject();// Save project (see lines at bottom of class)
			}
		});
		saveBtn.setToolTipText("Save");
		saveBtn.setImage(SWTResourceManager.getImage(MainWindow.class, "/pictures/Save.gif"));
		
		Button openBtn = new Button(toolbar, SWT.NONE);
		openBtn.setText("Open");
		openBtn.addSelectionListener(new SelectionAdapter()
		{
			@Override
			public void widgetSelected(SelectionEvent e)
			{
				newProject();// Remove current project (see lines at bottom of class)
				loadProject();// Load project (see lines at bottom of class)
			}
		});
		openBtn.setToolTipText("Load");
		openBtn.setImage(SWTResourceManager.getImage(MainWindow.class, "/pictures/Open.gif"));
		
		Button runBtn = new Button(toolbar, SWT.NONE);
		runBtn.addSelectionListener(new SelectionAdapter()
		{
			@Override
			public void widgetSelected(SelectionEvent e)
			{
				if (runnable)// Test to see if we are in the Execution Tab
				{
					runProject();// Run project (see lines at bottom of class)
				}
				else
				// We are in the code tab
				{
					// Notify the user why we can't run the program
					MessageBox error = new MessageBox(getShell());
					error.setMessage("Please open the Execution Tab before running your project");
					error.open();
				}
			}
		});
		runBtn.setText("Run");
		runBtn.setToolTipText("Run");
		runBtn.setImage(SWTResourceManager.getImage(MainWindow.class, "/pictures/Play.gif"));
		
		Button stopBtn = new Button(toolbar, SWT.NONE);
		stopBtn.addSelectionListener(new SelectionAdapter()
		{
			@Override
			public void widgetSelected(SelectionEvent e)
			{
				if (runnable)// Are we in Execution Tab
				{
					stopProject();// Stop Project
				}
			}
		});
		stopBtn.setText("Stop");
		stopBtn.setToolTipText("Stop");
		stopBtn.setImage(SWTResourceManager.getImage(MainWindow.class, "/pictures/Halt.gif"));
		
		final TabFolder tabFolder = new TabFolder(container, SWT.NONE);
		tabFolder.addSelectionListener(new SelectionAdapter()
		{
			@Override
			public void widgetSelected(SelectionEvent e)
			{
				// If we are in Execution Tab, make runnable true
				runnable = (tabFolder.getSelectionIndex() == 1) ? true : false;
				if (!runnable)// If we change to Code tab
				{
					stopProject();// Automatically stop the project
				}
			}
		});
		GridData gd_tabFolder = new GridData(SWT.LEFT, SWT.CENTER, true, true,
				1, 1);
		gd_tabFolder.heightHint = 2000;
		gd_tabFolder.widthHint = 3000;
		tabFolder.setLayoutData(gd_tabFolder);
		
		TabItem codingTab = new TabItem(tabFolder, SWT.NONE);
		codingTab.setText("Code");
		
		Composite codeTabArea = new Composite(tabFolder, SWT.NONE);
		codingTab.setControl(codeTabArea);
		formToolkit.paintBordersFor(codeTabArea);
		codeTabArea.setLayout(new GridLayout(2, false));
		
		codeBox = new Text(codeTabArea, SWT.BORDER | SWT.WRAP | SWT.V_SCROLL | SWT.MULTI);
		GridData gd_codeBox = new GridData(SWT.LEFT, SWT.TOP, true, true, 1, 1);
		gd_codeBox.heightHint = 2000;
		gd_codeBox.widthHint = 3000;
		codeBox.setLayoutData(gd_codeBox);
		formToolkit.adapt(codeBox, true, true);
		
		Composite browserArea = new Composite(codeTabArea, SWT.NONE);
		browserArea.setLayoutData(new GridData(SWT.LEFT, SWT.CENTER, false, true, 1, 1));
		formToolkit.adapt(browserArea);
		formToolkit.paintBordersFor(browserArea);
		GridLayout gl_browserArea = new GridLayout(1, false);
		gl_browserArea.marginWidth = 0;
		gl_browserArea.marginHeight = 0;
		browserArea.setLayout(gl_browserArea);
		
		Composite navButtons = new Composite(browserArea, SWT.NONE);
		navButtons.setLayout(new FillLayout(SWT.HORIZONTAL));
		GridData gd_navButtons = new GridData(SWT.LEFT, SWT.CENTER, false, false, 1, 1);
		gd_navButtons.widthHint = 250;
		navButtons.setLayoutData(gd_navButtons);
		formToolkit.adapt(navButtons);
		formToolkit.paintBordersFor(navButtons);
		
		Button btnBack = new Button(navButtons, SWT.NONE);
		btnBack.addSelectionListener(new SelectionAdapter()
		{
			@Override
			public void widgetSelected(SelectionEvent e)
			{
				browser.back(); // Go back to the last viewed page
			}
		});
		formToolkit.adapt(btnBack, true, true);
		btnBack.setText("Back");
		
		Button btnHome = new Button(navButtons, SWT.NONE);
		btnHome.addSelectionListener(new SelectionAdapter()
		{
			@Override
			public void widgetSelected(SelectionEvent e)
			{
				browser.setUrl(homeURL); // Go to the home page
			}
		});
		formToolkit.adapt(btnHome, true, true);
		btnHome.setText("Home");
		
		Button btnForward = new Button(navButtons, SWT.NONE);
		btnForward.addSelectionListener(new SelectionAdapter()
		{
			@Override
			public void widgetSelected(SelectionEvent e)
			{
				browser.forward(); // Go to the page we just "backed" out of
			}
		});
		formToolkit.adapt(btnForward, true, true);
		btnForward.setText("Forward");
		browser = new Browser(browserArea, SWT.BORDER);
		GridData gd_browser = new GridData(SWT.LEFT, SWT.CENTER, false, true, 1, 1);
		gd_browser.widthHint = 250;
		gd_browser.heightHint = 2000;
		browser.setLayoutData(gd_browser);
		browser.setUrl(homeURL);
		formToolkit.adapt(browser);
		formToolkit.paintBordersFor(browser);
		
		TabItem execTab = new TabItem(tabFolder, SWT.NONE);
		execTab.setText("Execution");
		
		Composite execTabArea = formToolkit
				.createComposite(tabFolder, SWT.NONE);
		execTab.setControl(execTabArea);
		formToolkit.paintBordersFor(execTabArea);
		execTabArea.setLayout(new GridLayout(2, false));
		
		display = new Composite(execTabArea, SWT.BORDER);
		display.addPaintListener(new PaintListener()
		{
			public void paintControl(PaintEvent e)
			{
				GC gc = e.gc; // Get appropriate Graphics Controller
				for (Line l : lines) // For each line to be drawn on the field
				{
					gc.setForeground(l.getColor()); // Choose color based on line
					gc.setLineAttributes(new LineAttributes(l.getWidth())); // Choose width based on line
					gc.drawLine(l.getX1(), l.getY1(), l.getX2(), l.getY2()); // Draw line
				}
			}
		});
		GridData gd_display = new GridData(SWT.LEFT, SWT.TOP, true, true, 1, 1);
		gd_display.heightHint = 2000;
		gd_display.widthHint = 3000;
		display.setLayoutData(gd_display);
		formToolkit.adapt(display);
		formToolkit.paintBordersFor(display);
		
		Composite llamaBank = new Composite(execTabArea, SWT.BORDER
				| SWT.V_SCROLL);
		GridData gd_llamaBank = new GridData(SWT.RIGHT, SWT.TOP, true, true,
				1, 1);
		gd_llamaBank.verticalIndent = 1;
		gd_llamaBank.widthHint = 273;
		gd_llamaBank.heightHint = 512;
		llamaBank.setLayoutData(gd_llamaBank);
		formToolkit.adapt(llamaBank);
		formToolkit.paintBordersFor(llamaBank);
		
		// Generate Llamas for Llama Bank
		objectLabels = new Llama[32];// Is really a 4x8 matrix of Llamas (extended Labels)
		// Each boolean in selectedObject corresponds to a llama. When the llama is selected, the corresponding boolean becomes true
		selectedObject = new boolean[32];
		int counter = 0;// Iterates through each Llama as we make them
		for (int i = 0; i < 4; i++)
		{
			for (int j = 0; j < 8; j++)
			{
				objectLabels[counter] = new Llama(llamaBank, 64 * i + 32, 64 * j + 32, 64, 64);// Place the llamas in the bank
				objectLabels[counter].setImage(defaultLlama);// Use the default llama image for bank llamas
				selectedObject[counter] = false;// Initially, none of the objects are selected
				objectLabels[counter].addMouseListener(new MouseAdapter()
				{
					public void mouseDown(MouseEvent e)
					{
						if (e.button == 1)// Left mouse click
						{
							for (int k = 0; k < 32; k++)
							{
								if (e.widget == objectLabels[k])
								{
									objectLabels[k].drawBorder();// Add a border
									// Change Background
									// Device device = Display.getCurrent();
									// Color newColor = new Color(device, 200, 200, 200);
									// objectLabels[k].setBackground(newColor);
									selectedObject[k] = true;// Set appropriate boolean to true
								}
								else
								{
									objectLabels[k].clearBorder();// Remove existing borders
									// Reset Background
									// Device device = Display.getCurrent();
									// Color newColor = device.getSystemColor(SWT.COLOR_WIDGET_BACKGROUND);
									// objectLabels[k].setBackground(newColor);
									selectedObject[k] = false;// Set all other booleans to false
								}
							}
						}
					}
				});
				counter++;// Go to next llama
			}
		}
		
		Composite execTextArea = new Composite(execTabArea, SWT.NONE);
		execTextArea.setLayout(new GridLayout(1, false));
		GridData gd_execTextArea = new GridData(SWT.LEFT, SWT.CENTER, true,
				true, 1, 1);
		gd_execTextArea.heightHint = 156;
		gd_execTextArea.widthHint = 3000;
		execTextArea.setLayoutData(gd_execTextArea);
		formToolkit.adapt(execTextArea);
		formToolkit.paintBordersFor(execTextArea);
		
		txtOutput = new Text(execTextArea, SWT.BORDER | SWT.READ_ONLY | SWT.WRAP
				| SWT.V_SCROLL);
		GridData gd_txtOutput = new GridData(SWT.LEFT, SWT.TOP, true, true,
				1, 1);
		gd_txtOutput.widthHint = 3000;
		gd_txtOutput.heightHint = 116;
		txtOutput.setLayoutData(gd_txtOutput);
		formToolkit.adapt(txtOutput, true, true);
		
		commandLine = new Text(execTextArea, SWT.BORDER);
		GridData gd_commandLine = new GridData(SWT.FILL, SWT.FILL, true,
				false, 1, 1);
		gd_commandLine.widthHint = 1000;
		commandLine.setLayoutData(gd_commandLine);
		commandLine.addKeyListener(new KeyAdapter()
		{
			@Override
			public void keyPressed(KeyEvent e)
			{
				if (e.keyCode == 13)// Enter button
				{
					echo(commandLine.getText());// Echo input
					interpretCommand(commandLine.getText());
					commandLine.setText("");// Clear input area for new input
				}
			}
		});
		formToolkit.adapt(commandLine, true, true);
		
		Composite execButtonsAndList = new Composite(execTabArea, SWT.BORDER);
		GridLayout gl_execButtonsAndList = new GridLayout(1, false);
		gl_execButtonsAndList.marginHeight = 0;
		gl_execButtonsAndList.marginWidth = 0;
		execButtonsAndList.setLayout(gl_execButtonsAndList);
		GridData gd_execButtonsAndList = new GridData(SWT.RIGHT, SWT.CENTER, false,
				false, 1, 1);
		gd_execButtonsAndList.heightHint = 156;
		gd_execButtonsAndList.widthHint = 273;
		execButtonsAndList.setLayoutData(gd_execButtonsAndList);
		formToolkit.adapt(execButtonsAndList);
		formToolkit.paintBordersFor(execButtonsAndList);
		
		Composite execButtons = new Composite(execButtonsAndList, SWT.NONE);
		execButtons.setLayout(new FillLayout(SWT.HORIZONTAL));
		GridData gd_execButtons = new GridData(SWT.LEFT, SWT.CENTER, false, false, 1, 1);
		gd_execButtons.widthHint = 273;
		execButtons.setLayoutData(gd_execButtons);
		formToolkit.adapt(execButtons);
		formToolkit.paintBordersFor(execButtons);
		
		Button btnAdd = new Button(execButtons, SWT.NONE);
		btnAdd.addSelectionListener(new SelectionAdapter()
		{
			@Override
			public void widgetSelected(SelectionEvent e)
			{
				// Check to see which, if any, llama has been selected
				int selected = -1;// Assume no llama is selected
				for (int i = 0; i < 32; i++)
				{
					if (selectedObject[i])
					{
						selected = i;// Llama[i] is currently selected
					}
				}
				if (selected == -1)// If no llama is selected
				{
					// Let the user know that they must select a llama to add to the field
					MessageBox messageDialog = new MessageBox(getShell());
					messageDialog.setText("Error");
					messageDialog.setMessage("No object selected.");
					messageDialog.open();
				}
				else
				// A llama is selected
				{
					Llama newLlama = new Llama(display, 50, 50, 91, 91);// Create a copy of that llama on the field
					newFieldLlama(newLlama);// Add llama to playing field
				}
			}
		});
		formToolkit.adapt(btnAdd, true, true);
		btnAdd.setText("Add");
		
		Button btnEdit = new Button(execButtons, SWT.NONE);
		formToolkit.adapt(btnEdit, true, true);
		btnEdit.setText("Edit");
		
		Button btnSave = new Button(execButtons, SWT.NONE);
		formToolkit.adapt(btnSave, true, true);
		btnSave.setText("Save");
		
		Button btnLoad = new Button(execButtons, SWT.NONE);
		formToolkit.adapt(btnLoad, true, true);
		btnLoad.setText("Load");
		
		listObjects = new List(execButtonsAndList, SWT.BORDER | SWT.V_SCROLL);
		listObjects.addMouseListener(new MouseAdapter()
		{
			public void mouseDown(MouseEvent e)
			{
				if (e.button == 3)// Right mouse click
				{
					int selectedItem = listObjects.getSelectionIndex();
					if (selectedItem != -1)// A list item is selected
					{
						for (Llama l : programObjects)// Find matching llama
						{
							if (l.name.equals(listObjects.getItem(selectedItem)) && !l.isDisposed())
							{
								Event event = new Event();
								event.button = 3;// right mouse click
								l.notifyListeners(SWT.MouseDown, event);// Pretend the user right-clicked the llama
							}
						}
					}
				}
			}
			
			public void mouseDoubleClick(MouseEvent e)
			{
				if (e.button == 1)// left mouse cliick
				{
					int selectedItem = listObjects.getSelectionIndex();
					if (selectedItem != -1)// A list item is selected
					{
						commandLine.append(listObjects.getItems()[selectedItem] + ".");
						commandLine.setFocus();// Place cursor in commandLine
					}
				}
			}
		});
		GridData gd_listObjects = new GridData(SWT.LEFT, SWT.CENTER, false, true, 1, 1);
		gd_listObjects.heightHint = 116;
		gd_listObjects.widthHint = 249;
		listObjects.setLayoutData(gd_listObjects);
		formToolkit.adapt(listObjects, true, true);
		
		return container;
	}
	
	/**
	 * Launch the application.
	 * 
	 * @param args
	 */
	public static void main(String args[])
	{
		try
		{
			MainWindow window = new MainWindow();// Create an instance of this window
			window.setBlockOnOpen(true);// Once we have opened the window, chill and wait for user input
			window.open();// Make the window visible to the user
			Display.getCurrent().dispose();// Once the user is done (Hits the close button), clear up the resorces associated with this window
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	/**
	 * Configure the shell.
	 * 
	 * @param newShell
	 */
	@Override
	protected void configureShell(Shell newShell)
	{
		newShell.setMinimumSize(new Point(700, 500));// Window can't be smaller than this
		newShell.setImage(SWTResourceManager.getImage(getClass(), "/pictures/Llama.gif"));
		super.configureShell(newShell);
		newShell.setText("KodeLlama");// Name the Window
	}
	
	/**
	 * Return the initial size of the window.
	 */
	@Override
	protected Point getInitialSize()
	{
		return new Point(700, 500);// Start at minimum size for smaller screens
	}
	
	/**
	 * Create a new project
	 */
	protected void newProject()
	{
		// Make sure the user saves if they want to
		MessageBox exit = new MessageBox(getShell(), SWT.ICON_QUESTION
				| SWT.YES | SWT.NO | SWT.CANCEL);
		exit.setText("Confirm Exit");
		exit.setMessage("Are you sure you want to close this project without saving?");
		int response = exit.open();
		
		if (response == SWT.CANCEL)
		{
			return;// Don't close the project
		}
		else if (response == SWT.NO)
		{
			boolean saved = saveProject();// Save the project then close the project
			if (!saved)// The user cancelled the save
			{
				return;// Don't close the project
			}
		}
		
		// "Close" the project. Basically, just reinitialize everything to its default value
		txtOutput.setText("");
		commandLine.setText("");
		codeBox.setText("");
		listObjects.removeAll();
		lines = new ArrayList<Line>();
		for (int i = 0; i < programObjects.size(); i++)
		{
			programObjects.get(i).dispose();// remove objects from the field
		}
		programObjects = new ArrayList<Llama>();
		display.redraw();
	}
	
	/**
	 * Save the current project
	 */
	private boolean saveProject()
	{
		FileDialog fd = new FileDialog(getShell(), SWT.SAVE);
		fd.setText("Save Project");
		fd.setFilterExtensions(new String[]
			{ "*.pgm" });
		String homefolder = System.getProperty("user.home");
		fd.setFilterPath(homefolder);
		fd.setOverwrite(true);
		String fileName = fd.open();
		
		if (fileName == null)// User cancelled or closed the File Dialog
		{
			return false;
		}
		
		try
		{
			File file = new File(fileName);// Open a file with that name
			FileOutputStream write = new FileOutputStream(file);// Open a reader of that file
			ObjectOutputStream out = new ObjectOutputStream(write);// Open a stream for objects
			
			out.writeInt(programObjects.size());// Used to know how many llamas to read out of file
			for (Llama llama : programObjects)
			{
				out.writeObject(llama.Data());// write data associated with each llama
			}
			out.writeInt(lines.size());// Used to know how many lines to read out of file
			for (Line line : lines)
			{
				out.writeObject(line);// write data associated with each line
			}
			out.writeBytes(codeBox.getText());// Because code is kind of important
			
			out.close();// Close Stream
			write.close();// Close reader
		}
		catch (Exception e) // Most likely, filename is invalid (this may be untrue, but I'm lazy and don't feel like checking)
		{
			e.printStackTrace();
			System.err.println(e.getMessage());
			// Let the user know possible ways to fix the error
			MessageBox error = new MessageBox(getShell(), SWT.OK);
			error.setText("File Error");
			error.setMessage("Error opening file. Please make sure the file " +
					"is not open in another program");
			error.open();
		}
		return true;
	}
	
	/**
	 * Open a project from the disk
	 */
	public void loadProject()
	{
		// Opens a file dialog for .pgm files in the user's home directory and ask the user to select a file
		FileDialog fd = new FileDialog(getShell(), SWT.OPEN);
		fd.setFilterExtensions(new String[]
			{ "*.pgm" });
		fd.setText("Open Project");
		String homefolder = System.getProperty("user.home");
		fd.setFilterPath(homefolder);
		String fileName = fd.open();
		
		if (fileName == null)// User cancelled or closed the File Dialog
		{
			return;
		}
		
		try
		{
			File file = new File(fileName);// Open a file with that name
			FileInputStream read = new FileInputStream(file);// Open a reader of that file
			ObjectInputStream in = new ObjectInputStream(read);// Open a stream to read file
			
			int progSize = in.readInt();// How many llamas are there?
			for (int i = 0; i < progSize; i++)
			{
				Llama l = new Llama((LlamaData) in.readObject(), display);// Instantiate llama based on saved data
				newFieldLlama(l);// Add llama to field
			}
			int linesSize = in.readInt();// How many lines are there?
			for (int i = 0; i < linesSize; i++)
			{
				Line line = (Line) in.readObject();// read in line object
				// Because color is transient, we reinstantiate it using the R, G, and B values
				line.setColor(new Color(display.getDisplay(), line.getR(), line.getG(), line.getB()));
				lines.add(line);// add line to field
			}
			String code = "";
			int i;
			while ((i = in.read()) != -1)
			{
				code += (char) i;// yay appending!
			}
			codeBox.setText(code);
			
			in.close();// Close stream
			read.close();// Close reader
		}
		catch (Exception e) // Most likely, file does not exist
		{
			e.printStackTrace();
			System.err.println(e.getMessage());
			// Let the user know possible ways to fix the error
			MessageBox error = new MessageBox(getShell(), SWT.OK);
			error.setText("File Error");
			error.setMessage("Error opening file. Please make sure the file exists and " +
					"is not open in another program");
			error.open();
			System.err.println(e.getMessage());
			loadProject();// Reopen file dialog
		}
	}
	
	/**
	 * Run the current project
	 */
	public void runProject()
	{
		// TODO Auto-generated method stub
		
	}
	
	/**
	 * Stop any running project
	 */
	public void stopProject()
	{
		// TODO Auto-generated method stub
		
	}
	
	/**
	 * Print something to the text output
	 */
	private void echo(String n)
	{
		txtOutput.append(n + "\n");// Basically, our version of System.out.println(n);
	}
	
	/**
	 * Check to see if a name is taken
	 */
	private boolean isTaken(String name, boolean verbal)
	{
		boolean isValid = true;
		for (int i = 0; i < programObjects.size(); i++)
		{
			if (programObjects.get(i).name.equals(name) && !programObjects.get(i).isDisposed())
			{
				// A non-disposed object is already using that name
				isValid = false;
				if (verbal)// We only display an error message some of the times
				{
					MessageBox error = new MessageBox(this.getShell(), SWT.ERROR);
					error.setText("Naming Error");
					error.setMessage("Error: That name has already been taken by another object");
					error.open();
				}
				break;
			}
		}
		return !isValid;
	}
	
	/**
	 * Send a command to the interpreter to be run
	 */
	protected void interpretCommand(String text)
	{
		if (!text.contains("("))
		{
			echo("Unrecognized Command");// Because parentheses are kind of important
			return;
		}
		if (text.substring(0, text.indexOf('(')).contains("."))
		{
			int index = -1;
			String object = text.substring(0, text.indexOf('.'));
			// Find the index of the object in the ArrayList
			for (int i = 0; i < programObjects.size(); i++)
			{
				if (programObjects.get(i).name.equals(object) && !programObjects.get(i).isDisposed())
				{
					index = i;
					break;
				}
			}
			
			if (index != -1)
			{
				echo(runCommand(commandLine.getText(), programObjects.get(index)));// Send command to interpreter
			}
			else
			{
				echo("No such object");// No object
			}
		}
		else
		{
			echo(runCommand(commandLine.getText(), null));
		}
	}
	
	/**
	 * Run a single command from the command line
	 */
	public String runCommand(String text, Llama llama)
	{
		String command = "";
		if (text.substring(0, text.indexOf('(')).contains("."))// Format of all known valid functions
		{
			command = "";
			String argument = "";
			// Separate command from object
			command = "";
			if (text.contains(" "))// Ignore anything after a space after the command
			{
				command = text.substring(text.indexOf('.') + 1, text.indexOf(' '));
			}
			else
			{
				command = text.substring(text.indexOf('.') + 1, text.length());
			}
			if (command.contains("("))
			{
				if (command.contains(")"))// Separate argument from command
				{
					argument = command.substring(command.indexOf('(') + 1, command.indexOf(')'));
					command = command.substring(0, command.indexOf('('));
				}
			}
			command = command.toLowerCase();
			argument = argument.toLowerCase();
			if (argument.equals(""))
			{
				/*
				 * back(int n) / bk(int n) done forward(int n) / fd(int n) done distance(Llama n) done lt(int n) / leftTurn(int n) done rt(int n) /
				 * rightTurn(int n) done infront() done behind() done pd() / penDown() done pu() / penUp() done position() / pos() done remove() - Will not be
				 * implemented; this should not be a method of the llama itself.
				 */
				if (command.equals("infront"))
				{
					for (Llama l : programObjects)
					{
						if (!l.isDisposed())
						{
							llama.moveAbove(l);// function of superclass
						}
					}
					return (llama.name + " has been placed in front.");
				}
				else if (command.equals("behind"))
				{
					for (Llama l : programObjects)
					{
						if (!l.isDisposed())
						{
							llama.moveBelow(l);// function of superclass
						}
					}
					return (llama.name + " has been placed behind.");
				}
				else if (command.equals("pd"))
				{
					llama.pd();
					return (llama.name + "'s pen is now down.");
				}
				else if (command.equals("pendown"))
				{
					llama.pd();
					return (llama.name + "'s pen is now down.");
				}
				else if (command.equals("pu"))
				{
					llama.pu();
					return (llama.name + "'s pen is now up.");
				}
				else if (command.equals("penup"))
				{
					llama.pu();
					return (llama.name + "'s pen is now up.");
				}
				else if (command.equals("position"))
				{
					Point objectPosition = llama.position();
					return (llama.name + "'s position is: " + objectPosition.toString());
				}
				else if (command.equals("pensize"))
				{
					return (llama.name + "'s penSize is: " + llama.penSize());
				}
				else if (command.equals("getx"))
				{
					Point objectPosition = llama.position();
					return (llama.name + "'s x-coordinate is: " + objectPosition.x);						
				}	
				else if (command.equals("gety"))
				{
					Point objectPosition = llama.position();
					return (llama.name + "'s y-coordinate is: " + objectPosition.y);
				}
			}
			else
			{
				int oldx = llama.x;
				int oldy = llama.y;
				if (command.equals("back"))
				{
					llama.back(Integer.parseInt(argument));
					if (llama.penDown)
					{
						Line line = new Line(llama.x, llama.y, oldx, oldy, llama.penSize, new Color(
								display.getDisplay(), llama.penColor));
						lines.add(line);
						display.redraw();
					}
					return (llama.name + " has been moved back " + argument + " pixels.");
				}
				else if (command.equals("bk"))
				{
					llama.back(Integer.parseInt(argument));
					if (llama.penDown)
					{
						Line line = new Line(llama.x, llama.y, oldx, oldy, llama.penSize, new Color(
								display.getDisplay(), llama.penColor));
						lines.add(line);
						display.redraw();
					}
					return (llama.name + " has been moved back " + argument + " pixels.");
				}
				else if (command.equals("forward"))
				{
					llama.forward(Integer.parseInt(argument));
					if (llama.penDown)
					{
						Line line = new Line(llama.x, llama.y, oldx, oldy, llama.penSize, new Color(
								display.getDisplay(), llama.penColor));
						lines.add(line);
						display.redraw();
					}
					return (llama.name + " has been moved forward " + argument + " pixels.");
				}
				else if (command.equals("fd"))
				{
					llama.forward(Integer.parseInt(argument));
					if (llama.penDown)
					{
						Line line = new Line(llama.x, llama.y, oldx, oldy, llama.penSize, new Color(
								display.getDisplay(), llama.penColor));
						lines.add(line);
						display.redraw();
					}
					return (llama.name + " has been moved forward " + argument + " pixels.");
				}
				else if (command.equals("distance"))
				{
					Llama a = llama;
					for (Llama l : programObjects)
					{
						if (l.name.equalsIgnoreCase(argument) && !l.isDisposed())
						{
							a = l;
							break;
						}
					}
					int distance = (int) Math.sqrt(Math.pow((a.x - llama.x), 2) + Math.pow((a.y - llama.y), 2));
					return (llama.name + " is " + distance + " pixels from " + a.name);
				}
				else if (command.equals("lt"))
				{
					llama.lt(Integer.parseInt(argument));
					return (llama.name + " has been turned left " + argument + " degrees.");
				}
				else if (command.equals("leftturn"))
				{
					llama.lt(Integer.parseInt(argument));
					return (llama.name + " has been turned left " + argument + " degrees.");
				}
				else if (command.equals("rt"))
				{
					llama.rt(Integer.parseInt(argument));
					return (llama.name + " has been turned right " + argument + " degrees.");
				}
				else if (command.equals("rightturn"))
				{
					llama.rt(Integer.parseInt(argument));
					return (llama.name + " has been turned right " + argument + " degrees.");
				}
				else if (command.equals("towards"))
				{
					Llama a = llama;
					for (Llama l : programObjects)
					{
						if (l.name.equalsIgnoreCase(argument) && !l.isDisposed())
						{
							a = l;
							break;
						}
					}
					llama.towards(a);
					return (llama.name + " has been turned towards " + a.name);
				}
				else if (command.equals("resize"))
				{
					llama.resize(Integer.parseInt(argument));
					return (llama.name + "'s pen resized to " + argument);
				}
			}
		}
		else
		{
			command = text.substring(0, text.indexOf('('));
			String argument = text.substring(text.indexOf('(') + 1);
			int ignore = 0;
			int charIndex = argument.length() - 1;
			for (int i = 0; i < argument.length(); i++)
			{
				if (argument.charAt(i) == '(')
				{
					ignore++;
				}
				if (argument.charAt(i) == ')')
				{
					if (ignore == 0)
					{
						charIndex = i;
						break;
					}
					ignore--;
				}
			}
			argument = argument.substring(0, charIndex);
			if (!command.equals("announce") && !command.equals("question") && !command.equals("show"))
			{
				argument = argument.replaceAll("[ )]", "");
			}
			// addLlama(Llama n) //Interpreter passes a llama to be added to the screen.
			// show(String s) //Display in text box
			// Turtle.COMMANDS //All turtle commands
			// colorUnder(Llama n) //Very low priority
			// touching(Llama n, Llama m) //Return true or false
			// freezeBg() //Very low priority
			// unFreezeBg() //Very low priority
			// announce(String s) //Display message dialog.
			// question(String s) //Display yes/no dialog and return true if yes and false if no.
			if (command.equals("addLlama"))
			{
				String[] args = argument.split(",");
				Llama arg = new Llama(display, Integer.parseInt(args[0]), Integer.parseInt(args[1]), 91, 91);
				newFieldLlama(arg); // add arg to field
				return (arg.name + " added to playing field");
			}
			else if (command.equals("show"))
			{
				return (argument);
			}
			else if (command.equals("colorUnder"))
			{
				int index = -1;
				for (int i = 0; i < programObjects.size(); i++)
				{
					if (programObjects.get(i).name.equals(argument) && !programObjects.get(i).isDisposed())
					{
						index = i;
						break;
					}
				}
				if (index == -1)
				{
					return (argument + " does not exist");
				}
				Llama arg1 = programObjects.get(index);
				for (int i = lines.size() - 1; i >= 0; i--)
				{
					if (lines.get(i).contains(arg1.position()))
					{
						return ("Color under " + argument + " is: (" + lines.get(i).getR() + ", " + lines.get(i).getG()
								+ ", " + lines.get(i).getB() + ")");
					}
				}
				return ("Color under " + argument + " is: (" + display.getBackground().getRed() + ", "
						+ display.getBackground().getGreen() + ", " + display.getBackground().getBlue() + ")");
			}
			else if (command.equals("touching"))
			{
				String[] args = argument.split(",");
				int index = -1;
				for (int i = 0; i < programObjects.size(); i++)
				{
					if (programObjects.get(i).name.equals(args[0]) && !programObjects.get(i).isDisposed())
					{
						index = i;
						break;
					}
				}
				if (index == -1)
				{
					return (args[0] + " does not exist");
				}
				Llama arg1 = programObjects.get(index);
				index = -1;
				for (int i = 0; i < programObjects.size(); i++)
				{
					if (programObjects.get(i).name.equals(args[1]) && !programObjects.get(i).isDisposed())
					{
						index = i;
						break;
					}
				}
				if (index == -1)
				{
					return (args[1] + " does not exist");
				}
				Llama arg2 = programObjects.get(index);
				Rectangle rect1 = new Rectangle(arg1.x, arg1.y, arg1.width, arg1.height);
				Rectangle rect2 = new Rectangle(arg2.x, arg2.y, arg2.width, arg2.height);
				if (rect1.intersects(rect2))
				{
					return "true";
				}
				else
				{
					return "false";
				}
			}
			else if (command.equals("freezeBg"))
			{
				// Store current state in variable
				frozenLines = new ArrayList<Line>();
				frozenLines.addAll(lines);
				frozen = true;
				return ("Background frozen");
			}
			else if (command.equals("unFreezeBg"))
			{
				// Clear variable
				frozenLines = new ArrayList<Line>();
				frozen = false;
				return ("Background unfrozen");
			}
			else if (command.equals("announce"))
			{
				String announceString = argument;
				MessageBox announceBox = new MessageBox(getShell(), SWT.ICON_INFORMATION
						| SWT.OK);
				announceBox.setText("Announcement");
				announceBox.setMessage(announceString);
				announceBox.open();
				return "";
			}
			else if (command.equals("question"))
			{
				String questionString = argument;
				MessageBox questionBox = new MessageBox(getShell(), SWT.ICON_QUESTION
						| SWT.YES | SWT.NO);
				questionBox.setText("Question");
				questionBox.setMessage(questionString);
				int response = questionBox.open();
				if (response == SWT.YES)
				{
					return "true";
				}
				else
				{
					return "false";
				}
			}
			else if (command.equals("clear"))
			{
				lines = new ArrayList<Line>();
				if (frozen)
				{
					lines.addAll(frozenLines);// Restore to stored state
				}
				display.redraw();
				return ("Background cleared");
			}
		}
		return ("Command not recognized: " + command);
	}
	
	/**
	 * Run a single command from the interpreter
	 */
	public Object execute(String text, Object[] args)
	{
		// That's right, we have two different functions to handle commands. Why? For the glory of Satan, of course!
		if (text.contains("."))
		{
			String object = text.substring(0, text.indexOf('.'));
			String command = "";
			String argument = "";
			int index = -1;
			// Find the index of the object in the ArrayList
			for (int i = 0; i < programObjects.size(); i++)
			{
				if (programObjects.get(i).name.equals(object) && !programObjects.get(i).isDisposed())
				{
					index = i;
					break;
				}
			}
			if (index != -1)
			{
				command = "";
				if (text.contains(" "))
				{
					command = text.substring(text.indexOf('.') + 1, text.indexOf(' '));
				}
				else
				{
					command = text.substring(text.indexOf('.') + 1, text.length());
				}
			}
			if (command.contains("("))
			{
				if (command.contains(")"))
				{
					argument = command.substring(command.indexOf('(') + 1, command.indexOf(')'));
					command = command.substring(0, command.indexOf('('));
				}
			}
			command = command.toLowerCase();
			argument = argument.toLowerCase();
			if (command.equals(""))
			{
				
			}
			else if (argument.equals(""))
			{
				/*
				 * back(int n) / bk(int n) done forward(int n) / fd(int n) done distance(Llama n) done lt(int n) / leftTurn(int n) done rt(int n) /
				 * rightTurn(int n) done infront() done behind() done pd() / penDown() done pu() / penUp() done position() / pos() done remove() - Will not be
				 * implemented; this should not be a method of the llama itself.
				 */
				if (command.equals("infront"))
				{
					programObjects.get(index).inFront();
				}
				else if (command.equals("behind"))
				{
					programObjects.get(index).behind();
				}
				else if (command.equals("pd"))
				{
					programObjects.get(index).pd();
				}
				else if (command.equals("pendown"))
				{
					programObjects.get(index).pd();
				}
				else if (command.equals("pu"))
				{
					programObjects.get(index).pu();
				}
				else if (command.equals("penup"))
				{
					programObjects.get(index).pu();
				}
				else if (command.equals("position"))
				{
					Point objectPosition = programObjects.get(index).position();
					return objectPosition;
				}
				else if (command.equals("penSize"))
				{
					return programObjects.get(index).penSize();
				}
				else if (command.equals("getx"))
				{
					Point objectPosition = programObjects.get(index).position();
					return objectPosition.x;										
				}	
				else if (command.equals("gety"))
				{
					Point objectPosition = programObjects.get(index).position();
					return objectPosition.y;										
				}
			}
			else
			{
				int oldx = programObjects.get(index).x;
				int oldy = programObjects.get(index).y;
				if (command.equals("back"))
				{
					programObjects.get(index).back(Integer.parseInt(argument));
					if (programObjects.get(index).penDown)
					{
						Line line = new Line(programObjects.get(index).x, programObjects.get(index).y, oldx, oldy,
								programObjects.get(index).penSize, new Color(display.getDisplay(),
										programObjects.get(index).penColor));
						lines.add(line);
						display.redraw();
					}
					
				}
				if (command.equals("bk"))
				{
					programObjects.get(index).back(Integer.parseInt(argument));
					if (programObjects.get(index).penDown)
					{
						Line line = new Line(programObjects.get(index).x, programObjects.get(index).y, oldx, oldy,
								programObjects.get(index).penSize, new Color(display.getDisplay(),
										programObjects.get(index).penColor));
						lines.add(line);
						display.redraw();
					}
					
				}
				if (command.equals("forward"))
				{
					programObjects.get(index).forward(Integer.parseInt(argument));
					if (programObjects.get(index).penDown)
					{
						Line line = new Line(programObjects.get(index).x, programObjects.get(index).y, oldx, oldy,
								programObjects.get(index).penSize, new Color(display.getDisplay(),
										programObjects.get(index).penColor));
						lines.add(line);
						display.redraw();
					}
				}
				if (command.equals("fd"))
				{
					programObjects.get(index).forward(Integer.parseInt(argument));
					if (programObjects.get(index).penDown)
					{
						Line line = new Line(programObjects.get(index).x, programObjects.get(index).y, oldx, oldy,
								programObjects.get(index).penSize, new Color(display.getDisplay(),
										programObjects.get(index).penColor));
						lines.add(line);
						display.redraw();
					}
				}
				if (command.equals("distance"))
				{
					Llama llama = programObjects.get(index);
					Llama a = llama;
					for (Llama l : programObjects)
					{
						if (l.name.equalsIgnoreCase(argument) && !l.isDisposed())
						{
							a = l;
							break;
						}
					}
					int distance = (int) Math.sqrt(Math.pow((a.x - llama.x), 2) + Math.pow((a.y - llama.y), 2));
					return distance;
				}
				if (command.equals("lt"))
				{
					programObjects.get(index).lt(Integer.parseInt(argument));
					
				}
				if (command.equals("leftturn"))
				{
					programObjects.get(index).lt(Integer.parseInt(argument));
					
				}
				if (command.equals("rt"))
				{
					programObjects.get(index).rt(Integer.parseInt(argument));
					
				}
				if (command.equals("rightturn"))
				{
					programObjects.get(index).rt(Integer.parseInt(argument));
					
				}
				if (command.equals("towards"))
				{
					Llama a = programObjects.get(index);
					for (Llama l : programObjects)
					{
						if (l.name.equalsIgnoreCase(argument) && !l.isDisposed())
						{
							a = l;
							break;
						}
					}
					programObjects.get(index).towards(a);
				}
				else if (command.equals("resize"))
				{
					programObjects.get(index).resize(Integer.parseInt(argument));
				}
			}
		}
		else
		{
			String command = text.substring(0, text.indexOf('('));
			// addLlama(Llama n) //Interpreter passes a llama to be added to the screen.
			// show(String s) //Display in text box
			// Turtle.COMMANDS //All turtle commands
			// colorUnder(Llama n) //Very low priority
			// touching(Llama n, Llama m) //Return true or false
			// freezeBg() //Very low priority
			// unFreezeBg() //Very low priority
			// announce(String s) //Display message dialog.
			// question(String s) //Display yes/no dialog and return true if yes and false if no.
			if (command.equals("addLlama"))
			{
				Llama arg = (Llama) args[0]; // Create new Llama from object
				newFieldLlama(arg); // Add llama to field
			}
			else if (command.equals("show"))
			{
				String arg = (String) args[0];
				echo(arg);
			}
			else if (command.equals("colorUnder"))
			{
				Llama arg1 = (Llama) args[0];
				for (int i = lines.size() - 1; i >= 0; i--)
				{
					if (lines.get(i).contains(arg1.position()))
					{
						return lines.get(i).getColor();
					}
				}
				return display.getBackground();
			}
			else if (command.equals("touching"))
			{
				Llama arg1 = (Llama) args[0];
				Llama arg2 = (Llama) args[1];
				Rectangle rect1 = new Rectangle(arg1.x, arg1.y, arg1.width, arg1.height);
				Rectangle rect2 = new Rectangle(arg2.x, arg2.y, arg2.width, arg2.height);
				return (rect1.intersects(rect2));
			}
			else if (command.equals("freezeBg"))
			{
				frozenLines = new ArrayList<Line>();
				frozenLines.addAll(lines);
				frozen = true;
			}
			else if (command.equals("unFreezeBg"))
			{
				frozenLines = new ArrayList<Line>();
				frozen = true;
			}
			else if (command.equals("announce"))
			{
				String announceString = (String) args[0];
				MessageBox questionBox = new MessageBox(getShell(), SWT.ICON_INFORMATION
						| SWT.OK);
				questionBox.setText("Announcement");
				questionBox.setMessage(announceString);
			}
			else if (command.equals("question"))
			{
				String questionString = (String) args[0];
				MessageBox questionBox = new MessageBox(getShell(), SWT.ICON_QUESTION
						| SWT.YES | SWT.NO);
				questionBox.setText("Question");
				questionBox.setMessage(questionString);
				int response = questionBox.open();
				return (response == SWT.YES);
			}
			else if (command.equals("clear"))
			{
				if (frozen)
				{
					lines = new ArrayList<Line>();
					lines.addAll(frozenLines);
				}
				display.redraw();
			}
		}
		return null;
	}
	
	/**
	 * Add a llama object to the playing field
	 */
	public void newFieldLlama(Llama l)
	{
		l.setImage(defaultLlama);// Use the image of the selected llama
		l.setBackground(null);
		final int spot = programObjects.size();// The index of the new llama in the ArrayList
		programObjects.add(l);// Add copy to the ArrayList
		int j = 0;
		l.name = "";
		do
		{
			if (!isTaken("Object" + (spot + j), false))
			{
				l.name = "Object" + (spot + j); // Store name in Llama
			}
			j++;
		} while (l.name.equals("")); // Keep trying higher numbers until you reach a name that isn't taken
		listObjects.add(l.name); // Add a corresponding entry to the list
		final Menu popupMenu = new Menu(programObjects.get(spot));// Create right-click menu for Field objects
		MenuItem nameItem = new MenuItem(popupMenu, SWT.NONE);
		nameItem.setText(l.name);
		nameItem.setEnabled(false);
		new MenuItem(popupMenu, SWT.SEPARATOR);
		MenuItem removeItem = new MenuItem(popupMenu, SWT.NONE);
		removeItem.setText("Remove");
		removeItem.addSelectionListener(new SelectionAdapter()
		{
			public void widgetSelected(SelectionEvent e)
			{
				// Remove llama from field
				Llama toRemove = programObjects.get(spot);
				toRemove.dispose();
				listObjects.remove(toRemove.name);
			}
		});
		MenuItem renameItem = new MenuItem(popupMenu, SWT.NONE);
		renameItem.setText("Rename");
		renameItem.addSelectionListener(new SelectionAdapter()
		{
			public void widgetSelected(SelectionEvent e)
			{
				InputDialog input = new InputDialog(display.getShell(), "Rename Llama",
						"Type a new name for your llama, than press OK", "", null);
				input.open();
				String name = input.getValue();
				if (name != null && !isTaken(name, true))
				{
					listObjects.setItem(listObjects.indexOf(programObjects.get(spot).name), name);
					programObjects.get(spot).name = name;
					programObjects.get(spot).getMenu().getItems()[0].setText(name);
				}
			}
		});
		MenuItem colorItem = new MenuItem(popupMenu, SWT.NONE);
		colorItem.setText("Set Color");
		colorItem.addSelectionListener(new SelectionAdapter()
		{
			public void widgetSelected(SelectionEvent e)
			{
				ColorDialog cd = new ColorDialog(getShell());
				cd.setRGB(programObjects.get(spot).penColor);
				programObjects.get(spot).penColor = cd.open();
			}
		});
		
		programObjects.get(spot).setMenu(popupMenu);// Associate menu with the object
		
		programObjects.get(spot).addDragDetectListener(new DragDetectListener()
		{
			public void dragDetected(DragDetectEvent arg0)
			{
				objectBeingDragged = spot;// Drag capability
			}
		});
		programObjects.get(spot).addMouseMoveListener(new MouseMoveListener()
		{
			public void mouseMove(MouseEvent arg0)
			{
				Llama moved = (Llama) arg0.widget;
				int mouseX = arg0.x;
				int mouseY = arg0.y;
				int objectX = moved.x;
				int objectY = moved.y;
				if (spot == objectBeingDragged && !outOfBounds(mouseX + objectX, mouseY + objectY))
				{
					// Have object follow mouse while being dragged
					// ((Llama) arg0.widget).setBounds(mouseX + objectX - 32, mouseY + objectY - 32, 64, 64);
					moved.x = mouseX - moved.width / 2 + objectX;
					moved.y = mouseY - moved.height / 2 + objectY;
					moved.refreshBounds();
				}
			}
			
			private boolean outOfBounds(int X, int Y)// Don't leave the playing field
			{
				Point size = display.getSize();// Get size of field
				if (X >= size.x/* right */|| Y >= size.y/* bottom */|| X < 0/* left */|| Y < 0/* top */)
				{
					return true;
				}
				return false;
			}
		});
		programObjects.get(spot).addMouseListener(new MouseAdapter()
		{
			public void mouseDown(MouseEvent e)
			{
				if (e.button == 3)// right mouse click
				{
					popupMenu.setVisible(true);// used for listObjects right click event
				}
			}
			
			public void mouseUp(MouseEvent e)
			{
				if (spot == objectBeingDragged)
				{
					objectBeingDragged = -1;// Release object from mouse
				}
			}
			
			public void mouseDoubleClick(MouseEvent e)
			{
				if (e.button == 1)// left mouse click
				{
					commandLine.append(programObjects.get(spot).name + ".");
					commandLine.setFocus();// put cursor in commandLine
				}
			}
		});
	}
}
